# Generated by Django 5.2.4 on 2025-07-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='email',
        ),
    ]
