# Generated by Django 5.2.4 on 2025-07-10 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique name for the ad placement (e.g., 'Homepage Top Banner', 'Product Detail Sidebar')", max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for the placement', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of where this ad placement appears', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this placement is currently active and can display ads')),
            ],
            options={
                'verbose_name': 'Ad Placement',
                'verbose_name_plural': 'Ad Placements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Title of the banner (e.g., 'Summer Sale!')", max_length=255)),
                ('image', models.ImageField(help_text='Upload the banner image', upload_to='marketing/banners/')),
                ('description', models.TextField(blank=True, help_text='Short description or call to action', null=True)),
                ('link_url', models.URLField(blank=True, help_text='URL to navigate to when banner is clicked', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which banners are displayed (lower number first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this banner is currently active and visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Override title for the advertisement', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Override description for the advertisement', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Date when the advertisement becomes active', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Date when the advertisement becomes inactive', null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which ads within a placement are displayed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this advertisement is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('placement', models.ForeignKey(help_text='The location where this advertisement will be displayed', on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='marketing.adplacement')),
                ('product', models.ForeignKey(blank=True, help_text='A featured product to highlight as an advertisement (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='core.product')),
                ('banner', models.ForeignKey(blank=True, help_text='The banner to display for this advertisement (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisements', to='marketing.banner')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
                'ordering': ['placement', 'display_order', '-created_at'],
            },
        ),
    ]
